version: "3.7"
services:
  nest:
    container_name: nest
    image: "famo1245/planj:v1"
    ports:
      - "3001:3000"
    networks:
      - backend
  nginx:
    container_name: nginx
    image: "famo1245/nginx:test"
    ports:
      - "80:80"
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks: # 가장 기본적인 bridge 네트워크
  backend:
    driver: bridge
